In [11]:
import pandas as pd
import spacy
from tqdm import tqdm
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# === Input ===
INPUT_CSV = "/Users/zphilipp/Downloads/search_queries.csv"
QUERY_COLUMN = "query"
DATE_COLUMN = "eventdate"

# === Output ===
ENTITIES_OUTPUT_CSV = "q2_location_entities.csv"
QUERIES_WITH_ENTITIES_CSV = "q2_queries_with_locations.csv"

# Step 1: load data for Q2 ===
print("Reading data...")
df = pd.read_csv(INPUT_CSV, parse_dates=[DATE_COLUMN])
df_q2 = df[df[DATE_COLUMN].dt.month.isin([4, 5, 6])].copy()
df_q2[QUERY_COLUMN] = df_q2[QUERY_COLUMN].fillna("").str.lower()
print(f"Počet dotazů v Q2: {len(df_q2):,}")
df_q2.head()

Reading data...
Počet dotazů v Q2: 12,704,541

,eventdate,division,query,search_count,clicks,orders
72338,2024-05-21,Minneapolis / St Paul,liposuction-surgery,1,0,0
72435,2024-04-01,abbotsford,massage,2,1,0
72436,2024-04-02,abbotsford,oil change,1,0,0
72437,2024-04-04,abbotsford,bartending,1,1,0
72438,2024-04-04,abbotsford,las vegas,1,0,0

In [12]:
nlp = spacy.load("en_core_web_sm")

# === Query analyze ===
print("I’m analyzing queries using ... NER...")
queries = df_q2[QUERY_COLUMN].dropna().unique().tolist()
location_entities = []
queries_with_entity = []

for doc in tqdm(nlp.pipe(queries, batch_size=100), total=len(queries)):
    ents = [ent.text.lower() for ent in doc.ents if ent.label_ in ("GPE", "LOC")]
    if ents:
        location_entities.extend(ents)
        queries_with_entity.append(doc.text)

# === Step 4: Outputs ===
total_queries = len(queries)
matched_queries = len(queries_with_entity)
coverage_percent = round(100 * matched_queries / total_queries, 2)

print(f"\n✅ Coverage: {matched_queries:,} / {total_queries:,} queries ({coverage_percent} % containts location)")

# Outpup 1: list of entities
entity_df = pd.Series(location_entities).value_counts().reset_index()
entity_df.columns = ["Location Entity", "Count"]
entity_df.to_csv(ENTITIES_OUTPUT_CSV, index=False)
print(f"📄 Entity saved to: {ENTITIES_OUTPUT_CSV}")
query_df.head(100)

I’m analyzing queries using ... NER...

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2074970/2074970 [22:28<00:00, 1539.02it/s]

✅ Coverage: 212,385 / 2,074,970 queries (10.24 % containts location)
📄 Entity saved to: q2_location_entities.csv

                                     query
0                                las vegas
1              mexico hotels all inclusive
2                  typhoon texas waterpark
3                              spa houston
4                         dreamhack dallas
5                                 kalahari
6                           dallas cowboys
7              great wolf lodge dallas, tx
8                                   greece
9                            resorts texas
10                       texas real estate
11                  texas rangers baseball
12                          virginia beach
13                        miramar beach fl
14                          michigan hotel
15                  park and fly cleveland
16                               asutralia
17                                  europe
18                      park n fly toronto
19                                  nuggmd
20                             berlin ohio
21               spray tans uniontown ohio
22                               san diego
23                                 georgia
24    fort myers fishing trip pure florida
25                            myrtle beach
26                         nassau, bahamas
27                             china house
28                         baltimore, ohio
29                   mamouth cave kentucky
30                     mgm northfield ohio
31                         texas roadhouse
32                   car rental akron ohio
33                             canton ohio
34                            canton, ohio
35                           berlin resort
36  pro football hall of fame canton, ohio
37                              ocean city
38                                  canton
39                  art gallery of toronto
40                          weed card ohio
41                      hotels in eric, pa
42                 golf in myrtle beach sc
43                           cleveland zoo
44                       laser zone canton
45                           new york city
46                         brunswick, ohio
47                            rhode island
48                               cleveland
49           mckinley presidential library
50                                 munford
51                                michigan
52               universal studios orlando
53                                 ashland
54                      massage akron ohio
55                               amsterdam
56              samana, dominican republic
57                  los angeles activities
58                          mt. washington
59                                 albany,
60                        aquatica orlando
61                         manhattan hotel
62                                new york
63                                    rome
64                    valvoline, delmar ny
65                          merida, mexico
66                          london ontario
67                             lebanon, nh
68                                 orlando
69                      six flags new york
70                     londenderry vermont
71               hotels in orlando florida
72                    south burlington, vt
73                          malta drive in
74           pauleys island south carolina
75                      karkhai water park
76                                 bahamas
77                        musical new york
78                           nyc city pass
79                        equinox  vermont
80                      dominican republic
81                             toronto zoo
82                    air bnb florida keys
83                               albany ny
84                             new zealand
85                           massachusetts
86                     hotels myrtle beach
87                          belmont stakes
88                       park n fly albany
89                    new york restaurants
90                          las vegas link
91                          hotel bronx ny
92                           atlantic city
93                          lebanon valley
94                                  albany
95               hollywood, beverly hills,
96                   tropical beach resort
97      new york roller coaster, las vegas
98                    wildlife zoo arizona
99                    las vegas helicopetr

In [13]:
# Output 2: list of queries
query_df = pd.DataFrame({QUERY_COLUMN: queries_with_entity})
query_df.to_csv(QUERIES_WITH_ENTITIES_CSV, index=False)
print(f"📄 Queries with locality saved as: {QUERIES_WITH_ENTITIES_CSV}")
query_df.head(100)

📄 Queries with locality saved as: q2_queries_with_locations.csv

                                     query
0                                las vegas
1              mexico hotels all inclusive
2                  typhoon texas waterpark
3                              spa houston
4                         dreamhack dallas
5                                 kalahari
6                           dallas cowboys
7              great wolf lodge dallas, tx
8                                   greece
9                            resorts texas
10                       texas real estate
11                  texas rangers baseball
12                          virginia beach
13                        miramar beach fl
14                          michigan hotel
15                  park and fly cleveland
16                               asutralia
17                                  europe
18                      park n fly toronto
19                                  nuggmd
20                             berlin ohio
21               spray tans uniontown ohio
22                               san diego
23                                 georgia
24    fort myers fishing trip pure florida
25                            myrtle beach
26                         nassau, bahamas
27                             china house
28                         baltimore, ohio
29                   mamouth cave kentucky
30                     mgm northfield ohio
31                         texas roadhouse
32                   car rental akron ohio
33                             canton ohio
34                            canton, ohio
35                           berlin resort
36  pro football hall of fame canton, ohio
37                              ocean city
38                                  canton
39                  art gallery of toronto
40                          weed card ohio
41                      hotels in eric, pa
42                 golf in myrtle beach sc
43                           cleveland zoo
44                       laser zone canton
45                           new york city
46                         brunswick, ohio
47                            rhode island
48                               cleveland
49           mckinley presidential library
50                                 munford
51                                michigan
52               universal studios orlando
53                                 ashland
54                      massage akron ohio
55                               amsterdam
56              samana, dominican republic
57                  los angeles activities
58                          mt. washington
59                                 albany,
60                        aquatica orlando
61                         manhattan hotel
62                                new york
63                                    rome
64                    valvoline, delmar ny
65                          merida, mexico
66                          london ontario
67                             lebanon, nh
68                                 orlando
69                      six flags new york
70                     londenderry vermont
71               hotels in orlando florida
72                    south burlington, vt
73                          malta drive in
74           pauleys island south carolina
75                      karkhai water park
76                                 bahamas
77                        musical new york
78                           nyc city pass
79                        equinox  vermont
80                      dominican republic
81                             toronto zoo
82                    air bnb florida keys
83                               albany ny
84                             new zealand
85                           massachusetts
86                     hotels myrtle beach
87                          belmont stakes
88                       park n fly albany
89                    new york restaurants
90                          las vegas link
91                          hotel bronx ny
92                           atlantic city
93                          lebanon valley
94                                  albany
95               hollywood, beverly hills,
96                   tropical beach resort
97      new york roller coaster, las vegas
98                    wildlife zoo arizona
99                    las vegas helicopetr