## Category important words & similarity search

In [1]:
import sqlite3
import pandas as pd
import numpy as np
import re
import nltk
#from nltk import bigrams, trigrams
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics.pairwise import cosine_similarity


#model = SentenceTransformer('/Users/zphilipp/git/research/relevance/models/sentence-transformer.model')
model = SentenceTransformer('all-MiniLM-L6-v2')
nltk.download('punkt')

#pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', 200)

db_path = '/Users/zphilipp/git/research/dealsdb/deals_db1.db'

prepositions_and_conjunctions = [
    "about", "above", "across", "after", "against", "along", "among", "around", "at",
    "before", "behind", "below", "beneath", "beside", "between", "beyond", "by",
    "during", "for", "from", "in", "inside", "into", "near", "of", "off", "on",
    "out", "outside", "over", "through", "throughout", "to", "toward", "under",
    "until", "up", "with", "within", "without", "and", "but", "or", "for", "nor",
    "so", "yet", "although", "because", "as", "since", "unless", "while", "when",
    "where", "after", "before", "the", "a"
]
pattern = r'\b(?:' + '|'.join(prepositions_and_conjunctions) + r')\b'

def remove_prepositions_and_conjunctions(text):
    cleaned_text = re.sub(pattern, '', text, flags=re.IGNORECASE)
    cleaned_text = re.sub(r'\d+', '', cleaned_text)
    return re.sub(r'\s+', ' ', cleaned_text).strip()

# Get Words for embeddings
#def get_words_for_embeddings(row):
#    words = []
#    for item in row:
#        words.append(item[0])
#    return words

/Users/zphilipp/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/zphilipp/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
[nltk_data] Downloading package punkt to /Users/zphilipp/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

#### Get all titles from Deals and Options text

In [2]:
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

sql_query = """
    SELECT
        d.customer_category_id,
        c.name,
        GROUP_CONCAT(d.title_general, ',') || ' ' || GROUP_CONCAT(o.title, ',') AS text
    FROM deals d
        JOIN customer_category c ON c.id=d.customer_category_id
        JOIN options o ON o.deal_id=d.id    
    GROUP BY customer_category_id

"""

# Execute the query and load the data into a DataFrame
df = pd.read_sql_query(sql_query, conn)
conn.close()

In [3]:
df.head()

,customer_category_id,name,text
0,,Hair Extensions & Wigs,"Elevate your look with a full set of hair extensions at 24K Beauty, offering up to 49% off for a glamorous transformation,Get premium Brazilian hair extensions at 3 Minutes To Arrival with free mi..."
1,00133db9-f9c6-46d4-bdfe-b72b82998560,Eyebrow Embroidery,"Achieve Stunning with Natural Eyelashes Extension at 1201 Beauty Bar and save (Up to 50% Off),Achieve Stunning with Natural Eyelashes Extension at 1201 Beauty Bar and save (Up to 50% Off),Achieve ..."
2,00dcb3b8-8176-4d67-85a5-4a64c56e2955,Escape Games,"Dive into A Murder Among Us with exciting at-home murder mysteries for 4+ people, offering up to 45% off,Dive into A Murder Among Us with exciting at-home murder mysteries for 4+ people, offering ..."
3,01ac7112-74e6-4757-b4b2-90be05a2884c,Wallets,"2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic Organizer,2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic Organizer,2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic..."
4,01be4a60-f74c-4181-b8bf-8b67afb32a74,Underwear & Undershirts,"4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & 2-Bottoms),4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & 2-Bottoms),4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & ..."

#### Count important words for each category

In [4]:
def to_trigrams(text):
    text = remove_prepositions_and_conjunctions(text)
    if isinstance(text, list):
        text = " ".join(text)
    elif not isinstance(text, str):
        return []

    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)

    words = nltk.word_tokenize(text)
    bigrams_list = list(nltk.trigrams(words))
    bigram_counts = Counter(bigrams_list)
    sorted_bigrams = bigram_counts.most_common()

    return sorted_bigrams[:10]
    
def to_bigrams(text):
    text = remove_prepositions_and_conjunctions(text)
    if isinstance(text, list):
        text = " ".join(text)
    elif not isinstance(text, str):
        return []

    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)

    words = nltk.word_tokenize(text)
    bigrams_list = list(nltk.bigrams(words))
    bigram_counts = Counter(bigrams_list)
    sorted_bigrams = bigram_counts.most_common()

    return sorted_bigrams[:10]
    
def get_important_words(document):
    document = remove_prepositions_and_conjunctions(document)
    document = [document]

    vectorizer = TfidfVectorizer(ngram_range=(1, 1))
    tfidf_matrix = vectorizer.fit_transform(document)

    feature_names = vectorizer.get_feature_names_out()
    first_document_vector = tfidf_matrix[0]
    important_words = sorted(
        [(feature_names[i], first_document_vector[0, i]) for i in first_document_vector.nonzero()[1]],
        key=lambda x: x[1], reverse=True
    )
    return important_words[:10]

#### Create word embedings and transform data

In [5]:
df_ = df
df_['important_words'] = df['text'].apply(get_important_words)
df_["bigrams"] = df["text"].apply(to_bigrams)
df_["trigrams"] = df["text"].apply(to_trigrams)

In [6]:
df_.head(10)

,customer_category_id,name,text,important_words,bigrams,trigrams
0,,Hair Extensions & Wigs,"Elevate your look with a full set of hair extensions at 24K Beauty, offering up to 49% off for a glamorous transformation,Get premium Brazilian hair extensions at 3 Minutes To Arrival with free mi...","[(women, 0.5013460125133989), (men, 0.3350842131068636), (xl, 0.3142541724821396), (pack, 0.20831153935286478), (sleeve, 0.1942726931595046), (black, 0.1813916899511638), (long, 0.1468345300905849...","[((long, sleeve), 9246), ((short, sleeve), 4613), ((sterling, silver), 4504), ((slim, fit), 3673), ((open, front), 3558), ((eau, de), 3368), ((apple, watch), 3196), ((extended, sizes), 3175), ((pl...","[((tshirts, extended, sizes), 2522), ((long, sleeve, shirt), 2098), ((extended, sizes, available), 1573), ((extended, sizes, availablemens), 1572), ((long, sleeve, shirts), 1355), ((army, camo, fo..."
1,00133db9-f9c6-46d4-bdfe-b72b82998560,Eyebrow Embroidery,"Achieve Stunning with Natural Eyelashes Extension at 1201 Beauty Bar and save (Up to 50% Off),Achieve Stunning with Natural Eyelashes Extension at 1201 Beauty Bar and save (Up to 50% Off),Achieve ...","[(extensions, 0.3950043026695996), (eyebrow, 0.32262131526941124), (set, 0.31228088849795577), (full, 0.2874638642464626), (lash, 0.27712343747500706), (one, 0.2667830107035516), (eyelash, 0.23369...","[((full, set), 98), ((eyelash, extensions), 70), ((eyebrow, extensions), 56), ((set, classic), 36), ((your, look), 30), ((lash, extensions), 29), ((volume, lash), 26), ((enhance, your), 25), ((hyb...","[((full, set, classic), 30), ((one, full, set), 14), ((extensionsone, full, set), 14), ((volume, lash, extensions), 12), ((set, classic, lash), 12), ((full, set, individual), 12), ((mink, eyelash,..."
2,00dcb3b8-8176-4d67-85a5-4a64c56e2955,Escape Games,"Dive into A Murder Among Us with exciting at-home murder mysteries for 4+ people, offering up to 45% off,Dive into A Murder Among Us with exciting at-home murder mysteries for 4+ people, offering ...","[(escape, 0.6554168439500331), (room, 0.5100300494198391), (people, 0.2206679826364433), (murder, 0.19455482051208808), (private, 0.18208637373199052), (valid, 0.16561861383374848), (experience, 0...","[((escape, room), 1264), ((murder, mystery), 350), ((private, escape), 308), ((escaperoomstyle, murder), 304), ((mystery, people), 262), ((escape, game), 258), ((murder, us), 254), ((room, experie...","[((escaperoomstyle, murder, mystery), 274), ((private, escape, room), 271), ((murder, mystery, people), 262), ((escape, room, experience), 235), ((escape, room, four), 143), ((four, six, eight), 1..."
3,01ac7112-74e6-4757-b4b2-90be05a2884c,Wallets,"2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic Organizer,2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic Organizer,2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic...","[(wallet, 0.533966078168827), (women, 0.34254427656113434), (card, 0.2820952865797577), (rfid, 0.23172112826194383), (blocking, 0.22164629659838103), (holder, 0.22164629659838103), (purse, 0.20149...","[((rfid, blocking), 32), ((card, holder), 27), ((emblem, wallet), 26), ((wallet, wrist), 26), ((collection, lisbette), 20), ((lisbette, embossed), 20), ((embossed, m), 20), ((m, signature), 20), (...","[((emblem, wallet, wrist), 26), ((collection, lisbette, embossed), 20), ((lisbette, embossed, m), 20), ((embossed, m, signature), 20), ((m, signature, womens), 20), ((signature, womens, wallet), 2..."
4,01be4a60-f74c-4181-b8bf-8b67afb32a74,Underwear & Undershirts,"4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & 2-Bottoms),4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & 2-Bottoms),4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & ...","[(piece, 0.39193833369309394), (men, 0.39193833369309394), (thermal, 0.39193833369309394), (set, 0.330970148451946), (winter, 0.27871170395953343), (top, 0.27871170395953343), (bottom, 0.278711703...","[((piece, winter), 64), ((winter, thermal), 64), ((thermal, top), 64), ((top, bottom), 64), ((bottom, set), 40), ((set, sizes), 40), ((sets, tops), 34), ((bottom, sets), 24), ((setmens, piece), 21...","[((piece, winter, thermal), 64), ((winter, thermal, top), 64), ((thermal, top, bottom), 64), ((top, bottom, set), 40), ((bottom, set, sizes), 40), ((top, bottom, sets), 24), ((bottom, sets, tops),..."
5,01bf112d-5431-45ed-808c-ab722d3b7d24,Basketball,"6.5 - 8ft Basketball Hoop For Kids,Basketball Hoop 5.6-6.5 FT Height Adjustable for Kids w/ Shatterproof Backboard,Costway 18"" Basketball Rim Wall Door Mounted Basketball Hoop with Net,Costway 18""...","[(basketball, 0.578243309582912), (hoop, 0.4497447963422649), (ft, 0.25699702648129424), (net, 0.25699702648129424), (costway, 0.22487239817113244), (adjustable, 0.17668545570588978), (backboard, ...","[((basketball, hoop), 20), ((all, weather), 8), ((basketball, net), 8), ((mounted, basketball), 6), ((ft, portable), 6), ((hoop, net), 6), ((height, adjustable), 4), ((w, shatterproof), 4), ((bask...","[((mounted, basketball, hoop), 6), ((basketball, hoop, net), 6), ((basketball, rim, wall), 4), ((rim, wall, door), 4), ((wall, door, mounted), 4), ((door, mounted, basketball), 4), ((ft, portable,..."
6,020fbaab-9a4b-4e5a-b1a1-854000bdb4ec,Pet Grooming,"Dog Bath Package for One Dog at A Day Of Doggie Beauty (Up to 32% Off),Dog Bath Package for One Dog at A Day Of Doggie Beauty (Up to 32% Off),Cleansing Bath, Teeth Brushing, Facial Scrub, and Nail...","[(grooming, 0.5424645206169905), (dog, 0.475099645507691), (pet, 0.29073261889276614), (bath, 0.28895985902146876), (package, 0.22336774378346666), (full, 0.195003585842709), (lbs, 0.1666394279019...","[((pet, grooming), 116), ((small, dog), 34), ((bathgrooming, package), 33), ((grooming, pet), 32), ((small, medium), 30), ((dog, grooming), 30), ((medium, dog), 29), ((grooming, package), 28), ((m...","[((small, medium, large), 26), ((lbsfull, bathgrooming, package), 24), ((grooming, pet, grooming), 19), ((service, dog, wash), 19), ((dog, lbsfull, bathgrooming), 18), ((package, medium, dog), 16)..."
7,0211a655-860a-4a05-9f74-02b2c17c6097,Home Theater Accessories,"US 10-20 Pcs 6.35mm 1/4"" Male to 3.5mm 1/8"" Female TRS Stereo Audio Adapter,US 10-20 Pcs 6.35mm 1/4"" Male to 3.5mm 1/8"" Female TRS Stereo Audio Adapter US 10-20 Pcs 6.35mm 1/4"" Male to 3.5mm 1/8"" ...","[(mm, 0.5601120336112039), (us, 0.28005601680560194), (pcs, 0.28005601680560194), (male, 0.28005601680560194), (female, 0.28005601680560194), (trs, 0.28005601680560194), (stereo, 0.280056016805601...","[((pcs, mm), 4), ((mm, male), 4), ((male, mm), 4), ((mm, female), 4), ((female, trs), 4), ((trs, stereo), 4), ((stereo, audio), 4), ((audio, adapter), 3), ((us, pcs), 2), ((adapter, pack), 2)]","[((pcs, mm, male), 4), ((mm, male, mm), 4), ((male, mm, female), 4), ((mm, female, trs), 4), ((female, trs, stereo), 4), ((trs, stereo, audio), 4), ((stereo, audio, adapter), 3), ((us, pcs, mm), 2..."
8,024d4f6c-d1d6-4ecd-905e-0f91c9b4ab54,Pilates,"At Anastasio, Discover a Boutique Wellness Haven Offering Private Pilates Sessions with Up to 25% Off,Achieve Your Fitness Goals with 5 or 10 Pilates Group Reformer Classes and Expert Instructors ...","[(pilates, 0.7513298273881077), (classes, 0.4507978964328646), (reformer, 0.2335214328368443), (private, 0.13808223854700358), (one, 0.13605161739190058), (sessions, 0.1319903750816946), (fitness,...","[((pilates, reformer), 54), ((pilates, classes), 43), ((reformer, classes), 37), ((private, pilates), 25), ((imx, pilates), 22), ((mat, pilates), 20), ((power, plate), 18), ((new, clients), 16), (...","[((pilates, reformer, classes), 15), ((private, pilates, gyrotonic), 10), ((your, fitness, journey), 10), ((reformer, pilates, classes), 8), ((eight, pilates, reformer), 8), ((three, pilates, equi..."
9,027fa496-5baf-4380-b829-5bb2294f70ac,Action Sports,"12'' x 12'' Acacia Wood Deck Patio Pavers Stripe Pattern,GoPowerBike GoVoyage 3-Wheel Kids Luggage Scooter with Light-Up Wheels,GoPowerBike GoVoyage 3-Wheel Kids Luggage Scooter with Light-Up Whee...","[(gopowerbike, 0.2870189239409639), (wheel, 0.2870189239409639), (scooter, 0.2870189239409639), (wheels, 0.2870189239409639), (govoyage, 0.19134594929397594), (kids, 0.19134594929397594), (luggage...","[((govoyage, wheel), 4), ((wheel, kids), 4), ((kids, luggage), 4), ((luggage, scooter), 4), ((scooter, light), 4), ((complete, skateboard), 4), ((skateboard, standard), 4), ((standard, skateboards...","[((govoyage, wheel, kids), 4), ((wheel, kids, luggage), 4), ((kids, luggage, scooter), 4), ((luggage, scooter, light), 4), ((complete, skateboard, standard), 4), ((skateboard, standard, skateboard..."

In [7]:
def combine_words(row):
    important_words_str = ' '.join(word[0] for word in row['important_words'])
    bigrams_str = ' '.join(' '.join(bigram[0]) for bigram in row['bigrams'])
    trigrams_str = ' '.join(' '.join(trigram[0]) for trigram in row['trigrams'])
    
    return pd.Series([important_words_str, bigrams_str, trigrams_str])
    
df_[['important_words_combined', 'bigrams_combined', 'trigrams_combined']] = df_.apply(combine_words, axis=1)
df_['combined_text'] = df_[['important_words_combined', 'bigrams_combined', 'trigrams_combined']].agg(' '.join, axis=1)
df_.head(5)

,customer_category_id,name,text,important_words,bigrams,trigrams,important_words_combined,bigrams_combined,trigrams_combined,combined_text
0,,Hair Extensions & Wigs,"Elevate your look with a full set of hair extensions at 24K Beauty, offering up to 49% off for a glamorous transformation,Get premium Brazilian hair extensions at 3 Minutes To Arrival with free mi...","[(women, 0.5013460125133989), (men, 0.3350842131068636), (xl, 0.3142541724821396), (pack, 0.20831153935286478), (sleeve, 0.1942726931595046), (black, 0.1813916899511638), (long, 0.1468345300905849...","[((long, sleeve), 9246), ((short, sleeve), 4613), ((sterling, silver), 4504), ((slim, fit), 3673), ((open, front), 3558), ((eau, de), 3368), ((apple, watch), 3196), ((extended, sizes), 3175), ((pl...","[((tshirts, extended, sizes), 2522), ((long, sleeve, shirt), 2098), ((extended, sizes, available), 1573), ((extended, sizes, availablemens), 1572), ((long, sleeve, shirts), 1355), ((army, camo, fo...",women men xl pack sleeve black long football shirt shirts,long sleeve short sleeve sterling silver slim fit open front eau de apple watch extended sizes plus size gold plated,tshirts extended sizes long sleeve shirt extended sizes available extended sizes availablemens long sleeve shirts army camo football eau de parfum white gold plated sleeve shirt sxl sizes availabl...,women men xl pack sleeve black long football shirt shirts long sleeve short sleeve sterling silver slim fit open front eau de apple watch extended sizes plus size gold plated tshirts extended size...
1,00133db9-f9c6-46d4-bdfe-b72b82998560,Eyebrow Embroidery,"Achieve Stunning with Natural Eyelashes Extension at 1201 Beauty Bar and save (Up to 50% Off),Achieve Stunning with Natural Eyelashes Extension at 1201 Beauty Bar and save (Up to 50% Off),Achieve ...","[(extensions, 0.3950043026695996), (eyebrow, 0.32262131526941124), (set, 0.31228088849795577), (full, 0.2874638642464626), (lash, 0.27712343747500706), (one, 0.2667830107035516), (eyelash, 0.23369...","[((full, set), 98), ((eyelash, extensions), 70), ((eyebrow, extensions), 56), ((set, classic), 36), ((your, look), 30), ((lash, extensions), 29), ((volume, lash), 26), ((enhance, your), 25), ((hyb...","[((full, set, classic), 30), ((one, full, set), 14), ((extensionsone, full, set), 14), ((volume, lash, extensions), 12), ((set, classic, lash), 12), ((full, set, individual), 12), ((mink, eyelash,...",extensions eyebrow set full lash one eyelash beauty microblading volume,full set eyelash extensions eyebrow extensions set classic your look lash extensions volume lash enhance your hybrid eyelash eyebrow microblading,full set classic one full set extensionsone full set volume lash extensions set classic lash full set individual mink eyelash extensions full set hybrid enhance your beauty lash extensions natural,extensions eyebrow set full lash one eyelash beauty microblading volume full set eyelash extensions eyebrow extensions set classic your look lash extensions volume lash enhance your hybrid eyelash...
2,00dcb3b8-8176-4d67-85a5-4a64c56e2955,Escape Games,"Dive into A Murder Among Us with exciting at-home murder mysteries for 4+ people, offering up to 45% off,Dive into A Murder Among Us with exciting at-home murder mysteries for 4+ people, offering ...","[(escape, 0.6554168439500331), (room, 0.5100300494198391), (people, 0.2206679826364433), (murder, 0.19455482051208808), (private, 0.18208637373199052), (valid, 0.16561861383374848), (experience, 0...","[((escape, room), 1264), ((murder, mystery), 350), ((private, escape), 308), ((escaperoomstyle, murder), 304), ((mystery, people), 262), ((escape, game), 258), ((murder, us), 254), ((room, experie...","[((escaperoomstyle, murder, mystery), 274), ((private, escape, room), 271), ((murder, mystery, people), 262), ((escape, room, experience), 235), ((escape, room, four), 143), ((four, six, eight), 1...",escape room people murder private valid experience game mystery home,escape room murder mystery private escape escaperoomstyle murder mystery people escape game murder us room experience valid any four six,escaperoomstyle murder mystery private escape room murder mystery people escape room experience escape room four four six eight flavor packhome escaperoomstyle packhome escaperoomstyle murder murd...,escape room people murder private valid experience game mystery home escape room murder mystery private escape escaperoomstyle murder mystery people escape game murder us room experience valid any...
3,01ac7112-74e6-4757-b4b2-90be05a2884c,Wallets,"2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic Organizer,2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic Organizer,2-Pack:Women's Travel Tote Handbag / Purse Insert Cosmetic...","[(wallet, 0.533966078168827), (women, 0.34254427656113434), (card, 0.2820952865797577), (rfid, 0.23172112826194383), (blocking, 0.22164629659838103), (holder, 0.22164629659838103), (purse, 0.20149...","[((rfid, blocking), 32), ((card, holder), 27), ((emblem, wallet), 26), ((wallet, wrist), 26), ((collection, lisbette), 20), ((lisbette, embossed), 20), ((embossed, m), 20), ((m, signature), 20), (...","[((emblem, wallet, wrist), 26), ((collection, lisbette, embossed), 20), ((lisbette, embossed, m), 20), ((embossed, m, signature), 20), ((m, signature, womens), 20), ((signature, womens, wallet), 2...",wallet women card rfid blocking holder purse leather travel organizer,rfid blocking card holder emblem wallet wallet wrist collection lisbette lisbette embossed embossed m m signature signature womens womens wallet,emblem wallet wrist collection lisbette embossed lisbette embossed m embossed m signature m signature womens signature womens wallet womens wallet mia travel tote handbag tote handbag purse handba...,wallet women card rfid blocking holder purse leather travel organizer rfid blocking card holder emblem wallet wallet wrist collection lisbette lisbette embossed embossed m m signature signature wo...
4,01be4a60-f74c-4181-b8bf-8b67afb32a74,Underwear & Undershirts,"4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & 2-Bottoms),4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & 2-Bottoms),4-Piece: Men's Premium Waffle Knit Thermal Sets (2-Tops & ...","[(piece, 0.39193833369309394), (men, 0.39193833369309394), (thermal, 0.39193833369309394), (set, 0.330970148451946), (winter, 0.27871170395953343), (top, 0.27871170395953343), (bottom, 0.278711703...","[((piece, winter), 64), ((winter, thermal), 64), ((thermal, top), 64), ((top, bottom), 64), ((bottom, set), 40), ((set, sizes), 40), ((sets, tops), 34), ((bottom, sets), 24), ((setmens, piece), 21...","[((piece, winter, thermal), 64), ((winter, thermal, top), 64), ((thermal, top, bottom), 64), ((top, bottom, set), 40), ((bottom, set, sizes), 40), ((top, bottom, sets), 24), ((bottom, sets, tops),...",piece men thermal set winter top bottom xl sizes sets,piece winter winter thermal thermal top top bottom bottom set set sizes sets tops bottom sets setmens piece sizes sxlmens,piece winter thermal winter thermal top thermal top bottom top bottom set bottom set sizes top bottom sets bottom sets tops setmens piece winter set sizes sxlmens sizes sxlmens piece,piece men thermal set winter top bottom xl sizes sets piece winter winter thermal thermal top top bottom bottom set set sizes sets tops bottom sets setmens piece sizes sxlmens piece winter thermal...

In [8]:
df_['combined_text'] = df_['combined_text'].tolist()
df_['combined_text_embeddings'] = df_['combined_text'].apply(lambda x: model.encode(x))

combined_embeddings = np.array(df_['combined_text_embeddings'].tolist())

In [9]:
def query_embedding_reduce(query_embedding):
    if query_embedding.shape[1] > 384:
        query_embedding_reduced = np.mean(query_embedding.reshape(-1, 2, 384), axis=1)
    else:
        query_embedding_reduced = query_embedding
    return query_embedding_reduced

df_[['name', 'customer_category_id', 'combined_text', 'combined_text_embeddings']].to_csv('models/category_embeding.csv')

df_.head(1)

,customer_category_id,name,text,important_words,bigrams,trigrams,important_words_combined,bigrams_combined,trigrams_combined,combined_text,combined_text_embeddings
0,,Hair Extensions & Wigs,"Elevate your look with a full set of hair extensions at 24K Beauty, offering up to 49% off for a glamorous transformation,Get premium Brazilian hair extensions at 3 Minutes To Arrival with free mi...","[(women, 0.5013460125133989), (men, 0.3350842131068636), (xl, 0.3142541724821396), (pack, 0.20831153935286478), (sleeve, 0.1942726931595046), (black, 0.1813916899511638), (long, 0.1468345300905849...","[((long, sleeve), 9246), ((short, sleeve), 4613), ((sterling, silver), 4504), ((slim, fit), 3673), ((open, front), 3558), ((eau, de), 3368), ((apple, watch), 3196), ((extended, sizes), 3175), ((pl...","[((tshirts, extended, sizes), 2522), ((long, sleeve, shirt), 2098), ((extended, sizes, available), 1573), ((extended, sizes, availablemens), 1572), ((long, sleeve, shirts), 1355), ((army, camo, fo...",women men xl pack sleeve black long football shirt shirts,long sleeve short sleeve sterling silver slim fit open front eau de apple watch extended sizes plus size gold plated,tshirts extended sizes long sleeve shirt extended sizes available extended sizes availablemens long sleeve shirts army camo football eau de parfum white gold plated sleeve shirt sxl sizes availabl...,women men xl pack sleeve black long football shirt shirts long sleeve short sleeve sterling silver slim fit open front eau de apple watch extended sizes plus size gold plated tshirts extended size...,"[0.0062530683, 0.010337821, 0.0054828557, 0.0057984474, 0.106226265, 0.045538425, 0.01654875, -0.0026985272, -0.050380968, -0.006734288, -0.041574314, -0.08526388, -0.004338309, -0.046334796, 0.07..."

In [10]:
def get_top_similarity(query_embedding_reduced, combined_embeddings):
    similarities = cosine_similarity(query_embedding_reduced, combined_embeddings).flatten()
    closest_indices = np.argsort(similarities)[-10:]

    closest_rows = []
    for index in reversed(closest_indices):
        #if similarities[index] > 0.27:
        
        closest_rows.append([df_.iloc[index], similarities[index]])

    return closest_rows

### Test query -> category use Cosine similarity of category embedings and query embedings

In [11]:
query_embedding_reduced = query_embedding_reduce(model.encode(['hair', 'cut']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Color & Highlights> -> score 0.4069351553916931
Closest Category: <Shave> -> score 0.3899712562561035
Closest Category: <Hair Salons> -> score 0.38908651471138
Closest Category: <Electrolysis Hair Removal> -> score 0.37771910429000854
Closest Category: <Barber Shop> -> score 0.35127004981040955
Closest Category: <Scalp & Hair Treatments> -> score 0.3498375415802002
Closest Category: <Shaving & Grooming> -> score 0.34928059577941895
Closest Category: <Hair Removal> -> score 0.3490675389766693
Closest Category: <Eyebrow Threading & Tint> -> score 0.348897784948349
Closest Category: <Blowouts & Styling> -> score 0.34643715620040894

In [12]:
query_embedding_reduced = query_embedding_reduce(model.encode(['oil']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Aromatherapy> -> score 0.3719143867492676
Closest Category: <Humidifiers> -> score 0.2833424508571625
Closest Category: <Interior Organization & Accessories> -> score 0.2786189913749695
Closest Category: <Pain Relief> -> score 0.27554085850715637
Closest Category: <Hot Stone Massage> -> score 0.2753846049308777
Closest Category: <Oil Change> -> score 0.27331608533859253
Closest Category: <Health & Beauty> -> score 0.2544480562210083
Closest Category: <Paint & Wallpapers> -> score 0.24660730361938477
Closest Category: <Oils & Tinctures> -> score 0.24642141163349152
Closest Category: <Athletic> -> score 0.23594920337200165

In [13]:
query_embedding_reduced = query_embedding_reduce(model.encode(['change']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Oil Change> -> score 0.2904558479785919
Closest Category: <Sporting Events> -> score 0.2694299519062042
Closest Category: <Personal Care> -> score 0.2570854425430298
Closest Category: <Sandboxes & Beach Toys> -> score 0.24860098958015442
Closest Category: <Pools & Water Fun> -> score 0.24503862857818604
Closest Category: <Grocery & Household> -> score 0.23550820350646973
Closest Category: <Changing Pads & Covers> -> score 0.2270347774028778
Closest Category: <Repair Services> -> score 0.2253355085849762
Closest Category: <Rhinoplasty> -> score 0.22375309467315674
Closest Category: <Hair Care Sets> -> score 0.2226557433605194

In [14]:
query_embedding_reduced = query_embedding_reduce(model.encode(['oil', 'change']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Oil Change> -> score 0.34907659888267517
Closest Category: <Sporting Events> -> score 0.2924673557281494
Closest Category: <Personal Care> -> score 0.2808721661567688
Closest Category: <Aromatherapy> -> score 0.28043466806411743
Closest Category: <Pain Relief> -> score 0.2674891948699951
Closest Category: <Bath Houses> -> score 0.26318100094795227
Closest Category: <Toys> -> score 0.26286599040031433
Closest Category: <Hair Care Sets> -> score 0.24186819791793823
Closest Category: <Sandboxes & Beach Toys> -> score 0.24068520963191986
Closest Category: <Treatments & Serums> -> score 0.24067071080207825

In [15]:
query_embedding_reduced = query_embedding_reduce(model.encode(['sauna', 'massage']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Saunas, Spas & Hot Tubs> -> score 0.5445180535316467
Closest Category: <Health Care> -> score 0.5400608777999878
Closest Category: <Couples Massage> -> score 0.5186799764633179
Closest Category: <Saunas> -> score 0.5099297761917114
Closest Category: <Hot Stone Massage> -> score 0.491965115070343
Closest Category: <Thai Massage> -> score 0.4902627468109131
Closest Category: <Classic Massage> -> score 0.48895013332366943
Closest Category: <Swedish Massage> -> score 0.48654428124427795
Closest Category: <Day Spas> -> score 0.4838810861110687
Closest Category: <Deep Tissue Massage> -> score 0.48230406641960144

In [16]:
query_embedding_reduced = query_embedding_reduce(model.encode(['oil', 'massage']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Hot Stone Massage> -> score 0.47305285930633545
Closest Category: <Couples Massage> -> score 0.46515953540802
Closest Category: <Health Care> -> score 0.45870572328567505
Closest Category: <Classic Massage> -> score 0.43880948424339294
Closest Category: <Thai Massage> -> score 0.41847890615463257
Closest Category: <Massage> -> score 0.4169067442417145
Closest Category: <Sports Massage> -> score 0.4116555452346802
Closest Category: <Massage Accessories> -> score 0.4092000126838684
Closest Category: <Deep Tissue Massage> -> score 0.40813931822776794
Closest Category: <Swedish Massage> -> score 0.40687239170074463

In [17]:
query_embedding_reduced = query_embedding_reduce(model.encode(['massage', 'oil']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Hot Stone Massage> -> score 0.47305285930633545
Closest Category: <Couples Massage> -> score 0.46515953540802
Closest Category: <Health Care> -> score 0.45870572328567505
Closest Category: <Classic Massage> -> score 0.43880948424339294
Closest Category: <Thai Massage> -> score 0.41847890615463257
Closest Category: <Massage> -> score 0.4169067442417145
Closest Category: <Sports Massage> -> score 0.4116555452346802
Closest Category: <Massage Accessories> -> score 0.4092000126838684
Closest Category: <Deep Tissue Massage> -> score 0.40813931822776794
Closest Category: <Swedish Massage> -> score 0.40687239170074463

In [18]:
query_embedding_reduced = query_embedding_reduce(model.encode(['valvoline', 'oil']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Oil Change> -> score 0.4157910943031311
Closest Category: <Paint & Wallpapers> -> score 0.29808247089385986
Closest Category: <Hot Stone Massage> -> score 0.29367271065711975
Closest Category: <Bath Houses> -> score 0.29340052604675293
Closest Category: <Boots & Booties> -> score 0.27371591329574585
Closest Category: <Health Care> -> score 0.26914283633232117
Closest Category: <Cosmetics> -> score 0.26889821887016296
Closest Category: <Couples Massage> -> score 0.2680445909500122
Closest Category: <Aromatherapy> -> score 0.2666873335838318
Closest Category: <Thai Massage> -> score 0.2547687292098999

In [19]:
query_embedding_reduced = query_embedding_reduce(model.encode(['water']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Volleyball> -> score 0.36758819222450256
Closest Category: <Water Bottles & Hydration> -> score 0.32667744159698486
Closest Category: <Boats & Water Sports> -> score 0.3225460648536682
Closest Category: <Athletic> -> score 0.3143218159675598
Closest Category: <Shoe Accessories> -> score 0.2954932153224945
Closest Category: <Pool & Water Fun> -> score 0.29200541973114014
Closest Category: <Fitness Technology> -> score 0.28234368562698364
Closest Category: <Water Filtration> -> score 0.2706008851528168
Closest Category: <Art Classes> -> score 0.26415902376174927
Closest Category: <Breweries, Wineries & Distilleries> -> score 0.25938278436660767

In [20]:
query_embedding_reduced = query_embedding_reduce(model.encode(['water', 'parks']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Boats & Water Sports> -> score 0.390032023191452
Closest Category: <Family> -> score 0.3873414993286133
Closest Category: <Jazz & Blues Clubs> -> score 0.3639675974845886
Closest Category: <Tents & Shelters> -> score 0.3511285185813904
Closest Category: <Water Bottles & Hydration> -> score 0.34523409605026245
Closest Category: <Volleyball> -> score 0.3392925560474396
Closest Category: <Running and Fun Runs> -> score 0.33666592836380005
Closest Category: <Bars> -> score 0.3343554437160492
Closest Category: <Amusement Parks> -> score 0.3305146396160126
Closest Category: <Ski Resorts> -> score 0.32996827363967896

In [21]:
query_embedding_reduced = query_embedding_reduce(model.encode(['amc']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Movies> -> score 0.3661923408508301
Closest Category: <Museums & Galleries> -> score 0.31634944677352905
Closest Category: <Comedy Clubs> -> score 0.31421276926994324
Closest Category: <Spa> -> score 0.3031492531299591
Closest Category: <Chainsaws> -> score 0.3018045425415039
Closest Category: <Mountains> -> score 0.29617464542388916
Closest Category: <Membership Clubs> -> score 0.2934684157371521
Closest Category: <Haunted Houses & Tours> -> score 0.29306328296661377
Closest Category: <Flight Tours> -> score 0.2922596335411072
Closest Category: <Amusement Parks> -> score 0.2897689938545227

In [22]:
query_embedding_reduced = query_embedding_reduce(model.encode(['pilates']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Pilates> -> score 0.4660865366458893
Closest Category: <Balance & Recovery> -> score 0.39877164363861084
Closest Category: <Massage> -> score 0.39685219526290894
Closest Category: <Tummy Tuck> -> score 0.3831145167350769
Closest Category: <Shiatsu Massage> -> score 0.3609078526496887
Closest Category: <Maternity> -> score 0.35589802265167236
Closest Category: <Outdoor Play> -> score 0.3388512432575226
Closest Category: <Shapewear> -> score 0.33686673641204834
Closest Category: <Weight Loss> -> score 0.3306010365486145
Closest Category: <Physical Therapy> -> score 0.3207736909389496

In [23]:
query_embedding_reduced = query_embedding_reduce(model.encode(['ring']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Collections & Sets> -> score 0.5369063019752502
Closest Category: <Personalized Rings> -> score 0.5006479024887085
Closest Category: <Rings> -> score 0.465104877948761
Closest Category: <Collections & Sets> -> score 0.4457462430000305
Closest Category: <Earrings> -> score 0.4284532070159912
Closest Category: <Necklaces> -> score 0.4264484941959381
Closest Category: <Necklaces> -> score 0.4131505489349365
Closest Category: <Earrings> -> score 0.41048431396484375
Closest Category: <Novelty> -> score 0.40886637568473816
Closest Category: <Collections> -> score 0.40432196855545044

In [24]:
query_embedding_reduced = query_embedding_reduce(model.encode(['wheel']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Tires & Wheels> -> score 0.4792405068874359
Closest Category: <Luggage Sets> -> score 0.42043086886405945
Closest Category: <Scooters, Skates & Skateboards> -> score 0.3985459506511688
Closest Category: <Balance Bikes & Pedal Cars> -> score 0.3885839581489563
Closest Category: <Electronic Toys> -> score 0.38349300622940063
Closest Category: <Riding Toys> -> score 0.3747599124908447
Closest Category: <Action Sports> -> score 0.3646172881126404
Closest Category: <Outdoor Power Equipment> -> score 0.35056841373443604
Closest Category: <Cardio Training> -> score 0.3370118737220764
Closest Category: <Baby Toys> -> score 0.3351131081581116

In [25]:
query_embedding_reduced = query_embedding_reduce(model.encode(['nail']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <No-Chip Manicure> -> score 0.4470480978488922
Closest Category: <Nail Designs> -> score 0.4419761002063751
Closest Category: <Manicure> -> score 0.44012683629989624
Closest Category: <No-Chip Mani & Reg Pedi> -> score 0.4215465784072876
Closest Category: <Pedicure> -> score 0.4170529842376709
Closest Category: <Mani Pedi> -> score 0.4108229875564575
Closest Category: <Baby Health & Grooming> -> score 0.3610284924507141
Closest Category: <Nail Salons> -> score 0.3181922733783722
Closest Category: <Massage Accessories> -> score 0.2845660448074341
Closest Category: <Halloween> -> score 0.2744731903076172

In [26]:
query_embedding_reduced = query_embedding_reduce(model.encode(['massage', 'palace']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Health Care> -> score 0.5500169992446899
Closest Category: <Couples Massage> -> score 0.4548746943473816
Closest Category: <Sports Massage> -> score 0.43926239013671875
Closest Category: <Hot Stone Massage> -> score 0.4283638000488281
Closest Category: <Day Spas> -> score 0.4248102903366089
Closest Category: <Swedish Massage> -> score 0.4165777564048767
Closest Category: <Classic Massage> -> score 0.411885142326355
Closest Category: <Deep Tissue Massage> -> score 0.411584734916687
Closest Category: <Thai Massage> -> score 0.4103524684906006
Closest Category: <Bath Houses> -> score 0.40090590715408325

In [27]:
query_embedding_reduced = query_embedding_reduce(model.encode(['apple', 'cider']).reshape(1, -1))
result = get_top_similarity(query_embedding_reduced, combined_embeddings)
for row in result:
    print(f"Closest Category: <{row[0]['name']}> -> score {row[1]}")

Closest Category: <Cables, Chargers & Adapters> -> score 0.3545122444629669
Closest Category: <Vitamins & Supplements> -> score 0.3496496081352234
Closest Category: <Cell Phone Accessories> -> score 0.3482317626476288
Closest Category: <Small Appliances> -> score 0.3474336862564087
Closest Category: <Hot Cocoa> -> score 0.3381025791168213
Closest Category: <TV Repair> -> score 0.32312503457069397
Closest Category: <Juices, Iced Tea & Milk> -> score 0.3202982544898987
Closest Category: <Health Care> -> score 0.31349819898605347
Closest Category: <Textured Hair Care> -> score 0.3104889392852783
Closest Category: <Baby Monitors> -> score 0.3084820806980133